# Generated by Django 5.2.12 on 2026-03-18 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages_crawled', models.IntegerField(default=0)),
                ('has_llms_txt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('h1', models.CharField(blank=True, max_length=500, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_noindex', models.BooleanField(default=False)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('json_ld_payload', models.JSONField(blank=True, null=True)),
                ('metadata_headers', models.JSONField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('depth', models.IntegerField(default=0)),
                ('priority', models.FloatField(default=0.5)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.crawljob')),
            ],
            options={
                'unique_together': {('job', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2000)),
                ('anchor_text', models.CharField(blank=True, max_length=500, null=True)),
                ('is_dofollow', models.BooleanField(default=True)),
                ('is_broken', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawler.crawljob')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='crawler.crawledpage')),
            ],
        ),
    ]
