# Generated by Django 5.2.12 on 2026-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='generated_llms_txt',
            field=models.FileField(blank=True, null=True, upload_to='llms_txts/'),
        ),
    ]
