# Generated by Django 5.2.12 on 2026-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawljob_generated_llms_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='generated_sitemap',
            field=models.FileField(blank=True, null=True, upload_to='sitemaps/'),
        ),
    ]
