# Generated by Django 5.2.12 on 2026-03-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawljob_generated_sitemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('orphan', 'Orphan Page'), ('broken_link', 'Broken Link'), ('canonical_conflict', 'Canonical Conflict'), ('noindex', 'Noindex in Sitemap'), ('duplicate_content', 'Duplicate Content'), ('schema_missing_coordinates', 'Missing Coordinates (LocalBusiness)'), ('schema_missing_sameas', 'Missing sameAs (Organization)'), ('schema_drift', 'Schema-to-Content Mismatch')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='crawler.crawljob')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='crawler.crawledpage')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('action_required', models.CharField(max_length=255)),
                ('business_impact', models.TextField()),
                ('affected_pages_count', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crawler.crawljob')),
            ],
        ),
    ]
