# Generated by Django 5.2.12 on 2026-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auditissue_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditissue',
            name='issue_type',
            field=models.CharField(choices=[('orphan', 'Orphan Page'), ('broken_link', 'Broken Link'), ('canonical_conflict', 'Canonical Conflict'), ('noindex', 'Noindex in Sitemap'), ('duplicate_content', 'Duplicate Content'), ('schema_missing_coordinates', 'Missing Coordinates (LocalBusiness)'), ('schema_missing_sameas', 'Missing sameAs (Organization)'), ('schema_drift', 'Schema-to-Content Mismatch'), ('eeat_missing_signal', 'Missing E-E-A-T Signal')], max_length=50),
        ),
    ]
