# Generated by Django 5.2.12 on 2026-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_auditissue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='redirect_chain_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='issue_type',
            field=models.CharField(choices=[('orphan', 'Orphan Page'), ('broken_link', 'Broken Link'), ('canonical_conflict', 'Canonical Conflict'), ('redirect_chain', 'Redirect Chain'), ('noindex', 'Noindex in Sitemap'), ('duplicate_content', 'Duplicate Content'), ('missing_sitemap', 'Missing from Sitemap'), ('schema_missing_coordinates', 'Missing Coordinates (LocalBusiness)'), ('schema_missing_sameas', 'Missing sameAs (Organization)'), ('schema_drift', 'Schema-to-Content Mismatch'), ('eeat_missing_signal', 'Missing E-E-A-T Signal')], max_length=50),
        ),
    ]
