# Generated by Django 5.2.12 on 2026-03-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_crawljob_target_keywords_alter_auditissue_issue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
