# Generated by Django 5.2.12 on 2026-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_alter_auditissue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='generated_llms_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawljob',
            name='generated_sitemap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
