# Generated by Django 5.2.12 on 2026-03-12 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sitemap_file', models.FileField(blank=True, null=True, upload_to='sitemaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
